# Generated by Django 3.0.5 on 2020-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='output',
            field=models.CharField(default='', max_length=500),
        ),
    ]
