from mongoengine import Document, EmbeddedDocument, fields
from datetime import datetime


# Create your models here.
class Dataset(EmbeddedDocument):
    # id is automatically generated by the engine
    name = fields.StringField(max_length=100)
    id_name = fields.StringField(max_length=100)
    author = fields.StringField(max_length=50)
    columns = fields.ListField()
    values = fields.ListField()


class Notebook(Document):
    # id is automatically generated by the engine
    author = fields.StringField(max_length=50)
    created_at = fields.DateTimeField(default=datetime.utcnow)
    datasets = fields.ListField(fields.EmbeddedDocumentField(Dataset))
    dataset_names = fields.ListField()
    dataset_columns = fields.DictField()
    output = fields.ListField()
