from mongoengine import Document, fields
from datetime import datetime


# Create your models here.
class Dataset(Document):
    # id is automatically generated by the engine
    id_name = fields.StringField(max_length=100)
    name = fields.StringField(max_length=100)
    author = fields.StringField(max_length=50)
    columns = fields.ListField()
    values = fields.ListField()


class Notebook(Document):
    # id is automatically generated by the engine
    author = fields.StringField(max_length=50)
    created_at = fields.DateTimeField(default=datetime.utcnow)
    dataset_ids = fields.ListField()
    dataset_names = fields.ListField()
    # Maybe combine the above two into a dictionairy? That would cause problems
    # in the frontend
    dataset_columns = fields.DictField()
    output = fields.ListField()
