from mongoengine import Document, fields
from datetime import datetime


# Create your models here.
class Dataset(Document):
    # id is automatically generated by the engine
    name = fields.StringField(max_length=100)
    author = fields.StringField(max_length=50)
    columns = fields.ListField()
    numerical_columns = fields.ListField()
    object_columns = fields.ListField()
    values = fields.ListField()


class Notebook(Document):
    # id is automatically generated by the engine
    author = fields.StringField(max_length=50)
    created_at = fields.DateTimeField(default=datetime.utcnow)
    datasets = fields.DictField()
    dataset_columns = fields.DictField()
    dataset_numerical_columns = fields.DictField()
    dataset_object_columns = fields.DictField()
    # Maybe do this the same way how you do it with the names/id's
    # Target is not to store these two/three fields in the future.
    output = fields.ListField()
